### PR TITLE
RF connectivity component

### PR DESCRIPTION
**Pull request by xgui3783**

### CODE REVIEW

**Comment by xgui3783** [comment]
hey @fsdavid , I did some refactoring of the connectivity component, but I am not 100% confident that the component still works in all circumstances.

Can you pull the branch and give some feed back on what doesn't work?

**Comment by fsdavid** [comment]
Sure, I will look at it

**Comment by fsdavid** [comment]
I see 2 major bugs:
1 - connectivity colors does not restore when region deselected from both - sidebar top close icon and from layer widget
2 - if we deselect region and then select any region again, connectivity automatically applies - also if we select and return from other parcellation

**Comment by xgui3783** [comment]
@fsdavid I have fixed the bugs you mentioned... I think

Wouldlove to hear if there are other bugs

**Comment by fsdavid** [comment]
Great, I think it has not more bugs.

**Pull request merged**
