### PR TITLE
Move drag&drop to nehuba container

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Comment by xgui3783** [comment]
Why is this change required?

**Comment by fsdavid** [comment]
> Why is this change required?

Because it is not possible to make drag&drop feature for plugins and everywhere outside Nehuba viewer.

**Comment by xgui3783** [comment]
Can you elaborate on drag and drop off plugin?

**Comment by fsdavid** [comment]
To import user landmarks, one of the ways is drag&drop. Currently, when the user drags the JSON file on the plugin, in parallel IAV expects to drop the file in it. 
image

**Pull request merged**
